# Generated by Django 5.2.4 on 2025-08-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homepage_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=50)),
                ('banner_image', models.ImageField(help_text='width 1520px by height 695px, try to maintain. This banner will be displayed in your homepage', upload_to='banner_image/')),
            ],
        ),
        migrations.CreateModel(
            name='homepage_banner_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.TextField(help_text='This text will be displayed over the Homepage banner image')),
                ('banner_message', models.TextField(blank=True, help_text='Below the banner title this message will be displayed', null=True)),
                ('target_page_link', models.CharField(choices=[('homepage', 'Homepage'), ('about_page', 'About Us page'), ('contact_page', 'Contact page'), ('programs_page', 'Programs page'), ('blog_page', 'Story page'), ('teacher_page', 'Teachers page'), ('events_page', 'Events page'), ('notice_page', 'Notice page'), ('registration_page', 'Registration Page'), ('course_registration_page', 'Course Registration Page')], help_text='Select the page this banner should link to. People will redirect to this page.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='our_features_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(help_text='provide 550px by 450px image for better preview', upload_to='feature_image/')),
                ('feature_name1', models.CharField(max_length=30)),
                ('feature_description1', models.TextField()),
                ('feature_name2', models.CharField(max_length=30)),
                ('feature_description2', models.TextField()),
                ('feature_name3', models.CharField(max_length=30)),
                ('feature_description3', models.TextField()),
                ('feature_name4', models.CharField(max_length=30)),
                ('feature_description4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='subscriber_mobile_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=11)),
                ('date_of_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='success_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.TextField()),
                ('story_background_image', models.ImageField(help_text='width 1520px by height 695px, try to maintain.', upload_to='background_story_image/')),
                ('story_youtube_video_link', models.TextField(help_text='provide a you-tube video link.People will show the story from your website.')),
                ('story_short_message', models.TextField(blank=True, null=True)),
                ('story_details', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
