# Generated by Django 5.2.4 on 2025-08-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner_about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_image', models.ImageField(help_text='width 1920px by height 650px, try to maintain 3:1', upload_to='banner_image/')),
                ('banner_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='banner_contact_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_image', models.ImageField(help_text='width 1920px by height 650px, try to maintain 3:1', upload_to='banner_image/')),
                ('banner_content', models.TextField(blank=True, null=True)),
                ('content_body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='details_about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about_page', models.CharField(max_length=100)),
                ('image_about_page', models.ImageField(help_text='width 1080px by height 600px, try to maintain 3:1', upload_to='about_image/')),
                ('short_content_about_page', models.TextField(blank=True, null=True)),
                ('details_content_about_page', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='leadership_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='provide image 400px by 300 px for better preview', upload_to='about_image/')),
                ('short_message', models.TextField(blank=True, help_text='short message to all', null=True)),
                ('details_message', models.TextField(blank=True, help_text='short message to all', null=True)),
                ('contact_email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_mobile', models.CharField(blank=True, help_text='like as 017******', max_length=50, null=True)),
                ('contact_location', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_facebook', models.TextField(blank=True, help_text='Provide the facbook link, if necessary.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='peoples_contact_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peoples_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('peoples_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stories_about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_stories', models.CharField(max_length=100)),
                ('story_short_content', models.TextField(blank=True, null=True)),
                ('story_details_content', models.TextField(blank=True, null=True)),
                ('story_youtube_video_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_registration_on_course_programm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(help_text='Select the type of admission (e.g., Academic or Admission).', max_length=20)),
                ('group', models.CharField(help_text='Select the group: Science, Humanities, or Commerce.', max_length=20)),
                ('batch_name', models.CharField(blank=True, help_text='Enter the name of the batch or program the student is enrolling in.', max_length=150, null=True)),
                ('student_name', models.CharField(help_text='Full name of the student as per official documents.', max_length=150)),
                ('guardian_name', models.CharField(help_text='Full name of parent or guardian.', max_length=100)),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth (e.g., YYYY-MM-DD).', null=True)),
                ('gender', models.CharField(blank=True, help_text='Student’s gender (Male, Female, or Other).', max_length=10, null=True)),
                ('religion', models.CharField(blank=True, help_text='Religion of the student.', max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, help_text="Student's blood group (e.g., A+, B-, O+).", max_length=3, null=True)),
                ('ssc_roll', models.CharField(blank=True, help_text='SSC exam roll number (if applicable).', max_length=50, null=True)),
                ('hsc_roll', models.CharField(blank=True, help_text='HSC exam roll number (if applicable).', max_length=50, null=True)),
                ('school_name', models.CharField(blank=True, help_text='Name of the school the student attended.', max_length=150, null=True)),
                ('college_name', models.CharField(blank=True, help_text='Name of the college the student attended.', max_length=150, null=True)),
                ('student_mobile', models.CharField(help_text='Active mobile number of the student.', max_length=20)),
                ('guardian_mobile', models.CharField(help_text='Active mobile number of the guardian or parent.', max_length=20)),
                ('email', models.CharField(blank=True, help_text="Student's email address (if available).", max_length=50, null=True)),
                ('nid_birth_number', models.CharField(blank=True, help_text='Birth certificate number or NID number of the student.', max_length=50, null=True)),
                ('present_address', models.TextField(help_text='Current address where the student lives.')),
                ('permanent_address', models.TextField(help_text='Permanent home address of the student.')),
                ('photo', models.ImageField(help_text='Upload a clear photo of the student.', upload_to='registered_student_photos/')),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the student registered (auto-filled).')),
            ],
        ),
        migrations.CreateModel(
            name='total_registered_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(max_length=50)),
                ('fathers_full_name', models.CharField(max_length=50)),
                ('student_mobile', models.CharField(max_length=16)),
                ('gurdian_mobile', models.CharField(max_length=16)),
                ('student_address', models.TextField()),
                ('school_name', models.TextField()),
                ('result', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=15)),
                ('registered_course_event', models.TextField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('student_image', models.ImageField(help_text='image from the registration', upload_to='student_image/')),
            ],
        ),
    ]
