# Generated by Django 5.2.4 on 2025-08-03 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_image', models.ImageField(help_text='width 1920px by height 650px, try to maintain 3:1', upload_to='banner_image/')),
                ('banner_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='blog_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_posted_by', models.CharField(help_text='name of the person who is written by.', max_length=30)),
                ('blog_title', models.CharField(max_length=110)),
                ('blog_image', models.ImageField(help_text='width 1920px by height 650px, try to maintain 3:1', upload_to='blog_image/')),
                ('blog_details', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='events_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_image', models.ImageField(help_text='width 1920px by height 650px, try to maintain 3:1', upload_to='banner_image/')),
                ('banner_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='events_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=60)),
                ('event_image', models.ImageField(help_text='width 1920px by height 650px, try to maintain 3:1', upload_to='event_image/')),
                ('write_about_event', models.TextField()),
                ('event_date_time', models.DateTimeField()),
                ('event_location', models.CharField(max_length=50)),
                ('event_deliverable', models.TextField(blank=True, help_text='what you will provide? like as free snacks, pen, notebook, file, scale', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notice_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_image', models.ImageField(help_text='width 1920px by height 650px, try to maintain 3:1', upload_to='banner_image/')),
                ('banner_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notice_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=100)),
                ('notice_details', models.TextField(blank=True, null=True)),
                ('notice_bullet_point', models.TextField(blank=True, null=True)),
                ('notice_file', models.FileField(blank=True, help_text='Provide image or pdf file that the user can download.', null=True, upload_to='notice_documents/')),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='blog_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=50)),
                ('commenter_mobile', models.CharField(max_length=20)),
                ('details_comments', models.TextField()),
                ('comments_date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notice_event_blog.blog_details')),
            ],
        ),
        migrations.CreateModel(
            name='event_speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=30)),
                ('speaker_designation', models.CharField(max_length=50)),
                ('speaker_photo', models.ImageField(help_text='Small image,80px by 80px', upload_to='speakers_image/')),
                ('event_for_speaker', models.ForeignKey(help_text='select the event for this speaker', on_delete=django.db.models.deletion.CASCADE, related_name='all_speakers', to='notice_event_blog.events_details')),
            ],
        ),
    ]
