# Generated by Django 5.2.4 on 2025-08-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image', models.ImageField(blank=True, help_text='width 450px by height 300px, try to maintain', null=True, upload_to='course_image/')),
                ('course_name_title', models.CharField(blank=True, max_length=100, null=True)),
                ('course_category', models.CharField(choices=[('admission', 'Admission'), ('academic', 'Academic')], default='admission', max_length=20)),
                ('course_under_group', models.CharField(blank=True, choices=[('science', 'Science'), ('humanities', 'Humanities'), ('commerce', 'Commerce')], help_text='In which gorup the course belong to.', max_length=20, null=True)),
                ('course_approximate_duration_month', models.IntegerField(blank=True, null=True)),
                ('course_class_duration_hour', models.IntegerField(blank=True, null=True)),
                ('course_fee', models.IntegerField(blank=True, null=True)),
                ('about_course', models.TextField(blank=True, help_text='Tells details about course in plain text', null=True)),
                ('course_highlight', models.TextField(blank=True, help_text='Write line by line important point about coruse. Like as how many class,model test, sheet, exam etc', null=True)),
                ('course_others_info', models.TextField(blank=True, help_text='Write extra messages.Such as how to apply,how you deal with fees and policy etc', null=True)),
                ('course_start_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='programm_background_banner_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_image', models.ImageField(help_text='width 1920px by height 650px, try to maintain 3:1', upload_to='banner_image/')),
                ('banner_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_background_banner_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_image', models.ImageField(help_text='width 1520px by height 350px, try to maintain', upload_to='banner_image/')),
                ('banner_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_image', models.ImageField(blank=True, help_text='width 450px by height 300px, try to maintain', null=True, upload_to='teacher_image/')),
                ('teacher_name', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_group', models.CharField(blank=True, choices=[('science', 'Science'), ('humanities', 'Humanities'), ('commerce', 'Commerce')], help_text='In which gorup the teacher take classes.', max_length=20, null=True)),
                ('teacher_university_subject', models.CharField(blank=True, help_text='Provide the current University and subject name of the teacher', max_length=100, null=True)),
                ('message_from_teacher', models.TextField(blank=True, help_text='if any guidance or message to all from teacher, please include', null=True)),
                ('experience_and_activities', models.TextField(blank=True, help_text='Write Line by Line all point.', null=True)),
                ('teacher_biography', models.TextField(blank=True, help_text='Write about teacher', null=True)),
                ('teacher_contact_email', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_contact_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_contact_location', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_contact_facebook', models.TextField(blank=True, help_text='Provide the facbook link of teacher if necessary.', null=True)),
                ('courses_teacher', models.ManyToManyField(related_name='teachers', to='teacher_and_programm.course_details')),
            ],
        ),
    ]
